### PR TITLE
Test copy if-match and if-none-match

### PR DESCRIPTION
**Pull request by gaul**
References #72.

Signed-off-by: Andrew Gaul andrew@gaul.org

### CODE REVIEW

**Comment by andrewgaul** [comment]
Rebased and narrowed to copy if-match and if-none-match.

**Comment by andrewgaul** [comment]
@yehudasa bump

**Comment by gaul** [comment]
@alimaredia bump

**Comment by alimaredia** [comment]
@gaul these look great. do you think it would be out of scope for this PR to write similar tests for [upload_part_copy](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.upload_part_copy) and add them to this PR? 

If you don't think so, I'll go ahead and merge this and then write some for `upload_part_copy` myself.

**Comment by gaul** [comment]
I opened #293 to track the suggested tests.

**Pull request merged**
