### PR TITLE
boto3_s3tests: add tests for lifecycle expiration header

### PR DESCRIPTION
**Pull request by mattbenjamin**
The response to a successful PUT or HEAD (or GET) of/on
an object matching any enabled lifecycle expiration rule should
include an x-amz-expiration header for the object.  The
x-amz-expiration header consists of an expiry-date, rule-id tuple
indicating the earliest matching rule and the corresponding
expiration date for the object.

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@yehudasa I agree;  I wasnt sure the consolidate code would be very reusable, but I'll revisit it.

**Comment by yehudasa** [comment]
@mattbenjamin my main issue here was that I could hardly figure out what was the difference. Consolidating should highlight that.

**Comment by mattbenjamin** [comment]
ok, I have an idea for it

**Comment by mattbenjamin** [comment]
@yehudasa how about that?

**Comment by mattbenjamin** [comment]
@yehudasa not to waste your time, but to you find the refactor acceptable?

**Comment by yehudasa** [comment]
@yehudasa yeah, already approved it

**Comment by yehudasa** [comment]
@mattbenjamin yeah, already approved it

**Comment by KhasanovBI** [comment]
Also Complete Multipart upload and PUT Object COPY returns this header

**Pull request merged**
