### PR TITLE
Fix cherry pick tracker 65651

### PR DESCRIPTION
**Pull request by galsalomon66**
#579 had conflicts with ceph-master.

### CODE REVIEW

**Comment by cbodley** [comment]
thanks, pending qa in https://pulpito.ceph.com/cbodley-2024-09-09_14:20:57-rgw-wip-cbodley-testing-distro-default-smithi/ with suite-branch https://github.com/cbodley/ceph/commits/wip-qa-rgw-s3tests-587

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/cbodley-2024-09-09_14:20:57-rgw-wip-cbodley-testing-distro-default-smithi/

valgrind issue -- not related 
```
<error>
  <unique>0xa3f1</unique>
  <tid>1</tid>
  <kind>Leak_DefinitelyLost</kind>
  <xwhat>
    <text>264 (8 direct, 256 indirect) bytes in 1 blocks are definitely lost in loss record 10 of 19</text>
    <leakedbytes>264</leakedbytes>
    <leakedblocks>1</leakedblocks>
  </xwhat>
  <stack>
    <frame>
      <ip>0x4846743</ip>
      <obj>/usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>operator new[](unsigned long)</fn>
      <dir>/builddir/build/BUILD/valgrind-3.23.0/coregrind/m_replacemalloc</dir>
      <file>vg_replace_malloc.c</file>
      <line>729</line>
    </frame>
    <frame>
      <ip>0x5FC0CC7</ip>
      <obj>/usr/lib64/librados.so.2.0.0</obj>
      <fn>librados::v14_2_0::Rados::aio_create_completion()</fn>
    </frame>
    <frame>
      <ip>0xC9E297</ip>
      <obj>/usr/bin/radosgw</obj>
      <fn>rgw::notify::publish_commit(rgw::sal::Object*, unsigned long, std::chrono::time_point&lt;ceph::real_clock, std::chrono::duration&lt;unsigned long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, std::__cxx11::basic
_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;, rgw::notify::reservation_t&amp;, DoutPrefixProvider const*)</fn>
    </frame>
    <frame>
      <ip>0xA0F528</ip>
      <obj>/usr/bin/radosgw</obj>
      <fn>rgw::sal::RadosNotification::publish_commit(DoutPrefixProvider const*, unsigned long, std::chrono::time_point&lt;ceph::real_clock, std::chrono::duration&lt;unsigned long, std::ratio&lt;1l, 1000000000l&gt; &gt; &gt; const&amp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&a
mp;, std::__cxx11::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt; const&amp;)</fn>
```

other error -- not related 
```
2024-09-09T07:41:06.663 INFO:teuthology.orchestra.run.smithi002.stdout:ERROR:   py: InvocationError for command /home/ubuntu/cephtest/ragweed.client.0/.tox/py/bin/python -m pip install --exists-action w .tox/.tmp/package/1/ragweed-0.0.1.zip (exited with code 1)
2024-09-09T07:41:06.675 DEBUG:teuthology.orchestra.run:got remote process result: 1
2024-09-09T07:41:06.675 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/contextutil.py", line 30, in nested
    vars.append(enter())
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__ 
    return next(self.gen)
  File "/home/teuthworker/src/github.com_galsalomon66_ceph_94421829f7b81be633c5be5e50acc84fe1bd4f9f/qa/tasks/ragweed.py", line 261, in run_tests
    toxvenv_sh(ctx, remote, args, label="ragweed tests against rgw")
  File "/home/teuthworker/src/github.com_galsalomon66_ceph_94421829f7b81be633c5be5e50acc84fe1bd4f9f/qa/tasks/ragweed.py", line 230, in toxvenv_sh
    return remote.sh(['source', activate, run.Raw('&&')] + args, **kwargs) 
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/orchestra/remote.py", line 97, in sh
    proc = self.run(**kwargs)
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/orchestra/remote.py", line 523, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/orchestra/run.py", line 455, in run
    r.wait()
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/orchestra/run.py", line 161, in wait
    self._raise_for_status()
  File "/home/teuthworker/src/git.ceph.com_teuthology_3752d3834a7b6cd13dc17dfaa6c2fd3658f3439a/teuthology/orchestra/run.py", line 181, in _raise_for_status
    raise CommandFailedError(
teuthology.exceptions.CommandFailedError: Command failed (ragweed tests against rgw) on smithi002 with status 1: "source /home/ubuntu/cephtest/tox-venv/bin/activate && cd /home/ubuntu/cephtest/ragweed.client.0 && RAGWEED_CONF=/home/ubuntu/cephtest/archive/ragweed.client.0.conf RAGWEED_STAGES=prepare,check BOTO_CONFIG=/home/ubuntu/cephtest/boto.cfg tox --sitepackages -- -v -m 'not fails_on_rgw'"
```

**Comment by cbodley** [comment]
https://tracker.ceph.com/issues/67986 is resolved, --rerun pending in https://pulpito.ceph.com/cbodley-2024-09-12_18:17:46-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
rerun's a pass, tyvm Gal

**Pull request merged**
