### PR TITLE
Json s3tests

### PR DESCRIPTION
**Pull request by galsalomon66**
- adding tests per JSON input types, which includes various SQL operators. 
- alignment of some of the test routines upon removing the XML tags(\<Payload\>\<Records\>\<Payload\>) from the s3select results.

### CODE REVIEW

**Comment by cbodley** [comment]
@galsalomon66 is this ready to merge?

**Comment by galsalomon66** [comment]
> @galsalomon66 is this ready to merge?

yes (tuethology ran with that)

**Review by cbodley — APPROVED** [review]

**Comment by galsalomon66** [comment]
@cbodley 
how to backport this PR (into reef)?

**Comment by cbodley** [comment]
similarly to how you cherry-picked to ceph-master, we'd cherry-pick to the ceph-reef branch. just be careful with the timing, so we don't introduce failures in other reef tests

**Comment by galsalomon66** [comment]
> similarly to how you cherry-picked to ceph-master, we'd cherry-pick to the ceph-reef branch. just be careful with the timing, so we don't introduce failures in other reef tests

ok
1. cherry-picked into ceph-reef (same as ceph-master). so  ...  i understand no tracker? no scripts for backport?
2. as for timing .... i guess both PR's should merge into reef at the same time.

**Pull request merged**
