### PR TITLE
jewel: Add a test case for setting acl on object with no version id specified.

### PR DESCRIPTION
**Pull request by zhangsw**
Part of backport tracker http://tracker.ceph.com/issues/19764

Fixes: http://tracker.ceph.com/issues/18923

Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangsw** [comment]
@smithfarm backport for  http://tracker.ceph.com/issues/18923

**Comment by smithfarm** [comment]
@oritwas @yehudasa Should we merge this now so the jewel 10.2.9 integration testing exercises it?

**Comment by smithfarm** [comment]
Don't merge it quite yet . . . looks like there will be a very quick 10.2.9 to fix an MDS issue.

**Comment by smithfarm** [comment]
Should have asked for the submitter to redo the cherry-pick with `-x` . . . oh, well. It's appears to be a cherry-pick of d6435f4f5f2e82eb307fe31ed6d07b46e88a8c46.

**Pull request merged**
