### PR TITLE
Static website testsuites

### PR DESCRIPTION
**Pull request by robbat2**
This brings in almost all of the static website testsuite. It DOES detect if the website mode is available in the RGW instance before trying those tests (and otherwise skips the tests).

Also includes some needed refactoring, and annotations of further tests that fail on AWS.

Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by robbat2** [comment]
@yehudasa Reping on merging this?

**Comment by yehudasa** [comment]
@robbat2 there's a regression in the test suite in this branch. I assume it's related to the cleanup. The following tests fail:

test_object_raw_put_write_access
test_object_raw_put_authenticated
test_object_write_check_etag

The error that we're getting is 411 (missing content length). For some reason it sends requests without content length (previously these requests had content length). There's no `Transfer-Encoding: chunked` either.

**Comment by robbat2** [comment]
@yehudasa 
commit 3fe372d fixes those 3 tests again; but I need to dig further as some of the other RGW merges seem to have broken more static sites tests :-(.

**Comment by robbat2** [comment]
@liewegas @yehudasa 
Please merge this when the following Ceph PRs go live:
https://github.com/ceph/ceph/pull/8633
https://github.com/ceph/ceph/pull/8669

**Comment by yehudasa** [comment]
@robbat2 merged this off github (had a minor conflict)

**Pull request merged**
