### PR TITLE
Cloud transition/tiering test cases

### PR DESCRIPTION
**Pull request by soumyakoduri**
Added few test cases for rgw cloud-transition/tiering feature. The sleep/waiting time in the tests may vary based on the I/O latency to the cloud endpoint.

Feature doc: https://docs.google.com/document/d/1IoeITPCF64A5W-UA-9Y3Vp2oSfz3xVQHu31GTu3u3Ug/edit#heading=h.4o1xyas8s23x

PR: https://github.com/ceph/ceph/pull/35100

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

### CODE REVIEW

**Comment by alimaredia** [comment]
@soumyakoduri why were these done in boto and not boto3? Does Boto3 not have the APIs to test this?

**Comment by soumyakoduri** [comment]
> @soumyakoduri why were these done in boto and not boto3? Does boto3 not have the APIs to test this?

Not exactly. lifecycle testcases were added in boto and I just extended the same for cloud tiering too. If thats going to be deprecated, I can work on moving all these cases (including previous ones) to boto3. Please suggest.

**Comment by alimaredia** [comment]
Yes, these tests should be moved to boto3. The tests left in boto are ones where boto3 doesn't have proper APIs (very rare from what I remember) or tests which pass in boto but do not pass in boto3. All s3-tests should be written in boto3.

**Comment by soumyakoduri** [comment]
> Yes, these tests should be moved to boto3. The tests left in boto are ones where boto3 doesn't have proper APIs (very rare from what I remember) or tests which pass in boto but do not pass in boto3. All s3-tests should be written in boto3.

okay thanks! Will move the testcases to boto3.

**Comment by soumyakoduri** [comment]
> @soumyakoduri why were these done in boto and not boto3? Does boto3 not have the APIs to test this?

Not exactly. lifecycle testcases were added in boto and I just extended the same for cloud tiering too. If thats going to be deprecated, I can work on moving all these cases (including previous ones) to boto3. Please suggest.

**Comment by soumyakoduri** [comment]
Created https://github.com/ceph/s3-tests/pull/380 with testcases moved to botos3

**Pull request closed without merging**
