### PR TITLE
Add test for muiltpart copy without 'x-amz-copy-source-range' header

### PR DESCRIPTION
**Pull request by malc0lm**
This pr is prepared for https://github.com/ceph/ceph/pull/20002.

### CODE REVIEW

**Comment by malc0lm** [comment]
@mattbenjamin

**Comment by malc0lm** [comment]
@mattbenjamin  can you review this pr, thanks.

**Comment by mattbenjamin** [comment]
@malc0lm yes, I'll try to incorporate this tomorrow--thanks for your work!

**Comment by mattbenjamin** [comment]
@malc0lm a version of your test ported to boto3 is here
./s3tests_boto3/functional/test_s3.py
will request we rebase it to be a commit by you

as above, I had trouble with AWS4 using the builtin boto2;  we'll presumably merge this later today tho

**Comment by alimaredia** [comment]
@malc0lm as part of my porting to these tests from boto2 -> boto3, I've added your new test into the tests I've written. You can see them here:

https://github.com/ceph/s3-tests/pull/210

**Comment by malc0lm** [comment]
@alimaredia ok, good job.

**Pull request merged**
