### PR TITLE
Add test case for POST with no Content-Type header

### PR DESCRIPTION
**Pull request by mattbenjamin**
Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
[mbenjamin@lemon s3-tests]$ S3TEST_CONF=/home/mbenjamin/dev/rgw/s3tests-1.conf ./virtualenv/bin/nosetests -v --collect-only s3tests.functional.test_s3:test_post_object_authenticated_no_content_type
s3tests.functional.test_s3.test_post_object_authenticated_no_content_type ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
[mbenjamin@lemon s3-tests]$ S3TEST_CONF=/home/mbenjamin/dev/rgw/s3tests-1.conf ./virtualenv/bin/nosetests -v  s3tests.functional.test_s3:test_post_object_authenticated_no_content_type
s3tests.functional.test_s3.test_post_object_authenticated_no_content_type ... ok

----------------------------------------------------------------------
Ran 1 test in 0.568s

OK

**Comment by cbodley** [comment]
@mattbenjamin i think this should target the master branch first, then get cherry-picked onto ceph-master from there

**Comment by ktdreyer** [comment]
Related to http://tracker.ceph.com/issues/20201

**Comment by cbodley** [comment]
cherry-picked onto ceph-master

**Pull request merged**
