### PR TITLE
Add test to check retain date is in iso 8601 format

### PR DESCRIPTION
**Pull request by dabukalam**
Signed-off-by: Danny Abukalam <danny@softiron.com>

### CODE REVIEW

**Comment by cbodley** [comment]
@dabukalam can you please retarget this PR against the `master` branch instead of `ceph-master`? we can merge to master asap, then cherry-pick to ceph-master once the original fix merges

**Comment by cbodley** [comment]
without the fix in https://github.com/ceph/ceph/pull/42273, the test fails with:
> isodate.isoerror.ISO8601Error: Unrecognised ISO 8601 date format: 'Fri, 15 Jul 2022 12:48:17 GM'

and passes with the fix 👍

**Comment by alimaredia** [comment]
@dabukalam just so I understand the test correctly, if the test fails it would fail on the line `isodate.parse_datetime(retain_date)` correct?

**Comment by dabukalam** [comment]
@alimaredia that's correct Ali, yes.

`parse_datetime()` will error out if it's not given a valid iso8601 date.

**Review by alimaredia — APPROVED** [review]

**Comment by cbodley** [comment]
cherry-picked to ceph-master

**Pull request merged**
