### PR TITLE
Test list_objects_v2 KeyCount with Delimiter

### PR DESCRIPTION
**Pull request by huww98**
Test for: https://github.com/ceph/ceph/pull/37396

Signed-off-by: 胡玮文 <huww98@outlook.com>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by cbodley** [comment]
@mattbenjamin it looks like we merged this test case to ceph-master without merging the fix in https://github.com/ceph/ceph/pull/37396, so it's causing test failures

**Comment by cbodley** [comment]
i force-pushed ceph-master to remove the commit

**Comment by mattbenjamin** [comment]
Ok, sorry.  Hopefully we can merge this one soon.

**Comment by huww98** [comment]
Now that https://github.com/ceph/ceph/pull/37396 has been merged. @mattbenjamin @cbodley Maybe you could do the cherry-pick as stated in https://github.com/ceph/ceph/pull/37396#issuecomment-705726925 now?

**Pull request merged**
