### PR TITLE
lc: test transition of plain null version

### PR DESCRIPTION
**Pull request by cbodley**
for validating the fix of https://tracker.ceph.com/issues/62013

### CODE REVIEW

**Comment by cbodley** [comment]
@alimaredia can you please review? this was used to validate https://github.com/ceph/ceph/pull/52684 which merged already. https://pulpito.ceph.com/cbodley-2023-09-19_15:51:51-rgw-wip-cbodley-testing-distro-default-smithi/ shows a recent run against main that includes this passing test case

**Comment by alimaredia** [comment]
This PR looks good, I don't see the test (` test_lifecycle_plain_null_version_current_transition`) running here though: http://qa-proxy.ceph.com/teuthology/cbodley-2023-09-19_15:51:51-rgw-wip-cbodley-testing-distro-default-smithi/7398232/teuthology.log. Am I missing something?

```
2023-09-19T16:11:40.683 INFO:teuthology.orchestra.run.smithi050.stdout:collecting ... collected 784 items / 764 deselected / 20 selected
2023-09-19T16:11:40.683 INFO:teuthology.orchestra.run.smithi050.stdout:
2023-09-19T16:11:40.958 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set PASSED           [  5%]
2023-09-19T16:11:41.117 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_get PASSED           [ 10%]
2023-09-19T16:11:41.281 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_get_no_id PASSED     [ 15%]
2023-09-19T16:11:41.434 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_id_too_long PASSED   [ 20%]
2023-09-19T16:11:41.630 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_same_id PASSED       [ 25%]
2023-09-19T16:11:41.791 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_invalid_status PASSED [ 30%]
2023-09-19T16:11:41.961 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_date PASSED      [ 35%]
2023-09-19T16:11:42.119 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_invalid_date PASSED [ 40%]
2023-09-19T16:11:42.334 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_noncurrent PASSED [ 45%]
2023-09-19T16:11:42.497 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_deletemarker PASSED [ 50%]
2023-09-19T16:11:42.666 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_filter PASSED    [ 55%]
2023-09-19T16:11:42.840 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_empty_filter PASSED [ 60%]
2023-09-19T16:11:43.057 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_multipart PASSED [ 65%]
2023-09-19T16:11:43.214 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_transition_set_invalid_date PASSED [ 70%]
2023-09-19T16:13:23.591 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_transition PASSED    [ 75%]
2023-09-19T16:15:23.941 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_transition_single_rule_multi_trans PASSED [ 80%]
2023-09-19T16:15:24.112 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_set_noncurrent_transition PASSED [ 85%]
2023-09-19T16:15:24.170 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_cloud_transition SKIPPED [ 90%]
2023-09-19T16:15:24.232 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_cloud_multiple_transition SKIPPED [ 95%]
2023-09-19T16:15:24.297 INFO:teuthology.orchestra.run.smithi050.stdout:s3tests_boto3/functional/test_s3.py::test_lifecycle_cloud_transition_large_obj SKIPPED [100%]
```

**Comment by cbodley** [comment]
> Am I missing something?

@alimaredia huh, the rgw/lifecycle suite is filtering out lifecycle_expiration tests. i'll test the rebased https://github.com/ceph/ceph/pull/52259 to fix that

**Comment by cbodley** [comment]
> s3tests_boto3/functional/test_s3.py::test_lifecycle_plain_null_version_current_transition PASSED [ 77%]

@alimaredia tested successfully in http://qa-proxy.ceph.com/teuthology/cbodley-2023-09-21_22:20:01-rgw-main-distro-default-smithi/7400419/teuthology.log with https://github.com/ceph/ceph/pull/52259 as suite-branch

**Review by alimaredia — APPROVED** [review]

**Pull request merged**
