### PR TITLE
Ceph master new

### PR DESCRIPTION
**Pull request by alimaredia**
This PR is ceph-master with the boto3 tests added, ss3 working for boto3, redundant boto2 tests removed, and boto3 life cycle expiration tests added.

This branch is being tested in teuthology and the DNM label will be removed once there is a clean run.

### CODE REVIEW

**Comment by cbodley** [comment]
once this passes qa, i'd prefer that you manually cherry-pick the commits so we don't have extra merge commits on the release branches

**Comment by alimaredia** [comment]
Here is a QA run (http://pulpito.ceph.com/amaredia-2019-04-23_15:17:10-rgw:verify-master-distro-basic-smithi/). 

The ones with Valgrind errors are fine, just search for "OK (SKIP=79)".

@cbodley Once you approve the review of this PR then I will force push this branch as the new ceph-master branch.

**Comment by cbodley** [comment]
can you please run the full rgw suite?

**Comment by alimaredia** [comment]
@cbodley here are some more test runs:
The whole RGW suite with subset at 1/2: http://pulpito.ceph.com/amaredia-2019-04-25_20:24:47-rgw-master-distro-basic-smithi/
The whole RGW:Verify suite with subset at 1/2: http://pulpito.ceph.com/amaredia-2019-04-25_10:46:17-rgw:verify-master-distro-basic-smithi/

**Pull request merged**
