### PR TITLE
add s3select filter to tests

### PR DESCRIPTION
**Pull request by galsalomon66**
Signed-off-by: gal salomon <gal.salomon@gmail.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
I dont understand how the 2 commits in this PR match the title "skip s3select tests due to repeating errors"--there is a bunch of new test logic

**Comment by cbodley** [comment]
something like "tag s3select tests for filtering" may be a better title

**Comment by galsalomon66** [comment]
agree, title is wrong

**Comment by cbodley** [comment]
@galsalomon66 can you please rebase away the extra merge commit?

**Comment by galsalomon66** [comment]
move the change to new PR
https://github.com/ceph/s3-tests/pull/353

**Pull request closed without merging**
