### PR TITLE
s3select: align s3select tests with ceph

### PR DESCRIPTION
**Pull request by albin-antony**
Signed-off-by: Albin Antony <aantony@redhat.com>

### CODE REVIEW

**Review by galsalomon66 — APPROVED** [review]

**Comment by mattbenjamin** [comment]
@albin-antony I'm confused, github is reporting conflicts

**Comment by albin-antony** [comment]
> @albin-antony I'm confused, github is reporting conflicts

@mattbenjamin This pr can be merged only after merging the latest s3select to ceph. s3-tests master branch is in sync with the latest s3select. Resolving conflicts now will result in failure of some tests.

**Comment by galsalomon66** [comment]
> @albin-antony I'm confused, github is reporting conflicts

@mattbenjamin 

yes, it need to wait until https://github.com/ceph/ceph/pull/40910(new s3select features) is merged 
s3test/master is aligned with that PR.

once that PR(40910) is merged (and s3test) , this PR will rebase.

**Comment by galsalomon66** [comment]
please rebase the PR

**Comment by albin-antony** [comment]
Merged to #402

**Pull request closed without merging**
