### PR TITLE
add lifecycle validate test cases.

### PR DESCRIPTION
**Pull request by zhangsw**
Lifecycle validation is add in https://github.com/ceph/ceph/pull/12750. 
S3test need some test cases about that. The error status and error code are the same as S3.

Fixes: http://tracker.ceph.com/issues/18541
Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangsw** [comment]
@dang yes， I have tested and they are passed.

**Comment by dang** [comment]
LGTM, then.  Please merge after https://github.com/ceph/ceph/pull/12750

**Comment by zhangsw** [comment]
@dang could this be merged now?

**Comment by zhangsw** [comment]
@yehudasa Could this be merged now? I'd like to add some cases for non current version expiration which will  rely on this pr.

**Comment by dang** [comment]
@zhangsw I don't have permission to merge here.  @yehudasa will need to do it.

**Pull request merged**
