### PR TITLE
Add a test case for continuation token in list objects v2

### PR DESCRIPTION
**Pull request by zhangsw**
This is for https://github.com/ceph/ceph/pull/28988

Signed-off-by: zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by albIN7** [comment]
@zhangsw amazon s3 uses startafter to start listing the objects. So, I think it's better to assign startafter as 'baz' and continuationtoken as 'foo' and check whether the remaining key is 'quxx'. Does this makes sense?

**Comment by zhangsw** [comment]
@albIN7 If we specify both startafter and continuationtoken , S3 will ignore the startafter parameter. So as Ceph does. https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by albIN7** [comment]
> @albIN7 If we specify both startafter and continuationtoken , S3 will ignore the startafter parameter. So as Ceph does. https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

I have tested just now and it is working fine. Could you please test by specifying both startafter and continuationtoken and let me know the output.

**Comment by albIN7** [comment]
@zhangsw I think we should use startafter for listing the first object and continuationtoken for the subsequent objects though continuationtoken works even for listing the first object.

**Comment by zhangsw** [comment]
@albIN7 I add a new test case for specifying both startafter and continuationtoken and it works fine.

**Comment by alimaredia** [comment]
@zhangsw I think we're missing another test where the continuation token is "bad", aka not a string that's in the list of keys. 

@albIN7 what do you think?

**Comment by zhangsw** [comment]
@alimaredia I find that the continuationtoken is obfuscated and is not a real key in S3. If we provide a bad token, S3 will return: ```The continuation token provided is incorrect (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument)``` At present `continuationtoken` works just like a marker in Ceph. Maybe we can add the case when we make the `continuationtoken` work as S3's.

**Pull request merged**
