### PR TITLE
rgw/logging: basic set of tests for bucket logging

### PR DESCRIPTION
**Pull request by yuvalif**
bucket logging is implemented here:  https://github.com/ceph/ceph/pull/59808
~~https://github.com/ceph/ceph/pull/54815~~

### CODE REVIEW

**Comment by yuvalif** [comment]
* add versioned bucket tests

**Comment by yuvalif** [comment]
test is passing. see: https://github.com/ceph/ceph/pull/60700#issuecomment-2493444419

**Comment by cbodley** [comment]
why is it necessary to duplicate the s3 extensions file from the ceph repo? i'd rather not worry about trying to keep those in sync

**Comment by yuvalif** [comment]
> why is it necessary to duplicate the s3 extensions file from the ceph repo? i'd rather not worry about trying to keep those in sync

the other (and better) option is to fetch it from the ceph repo, but in my case I had to have a way to fetch it from a branch on my ceph fork.

**Comment by cbodley** [comment]
cherry-picked to ceph-master

**Pull request merged**
